In [1]:
import pandas as pd 
import numpy as np

In [2]:
df=pd.read_csv('data_science_job.csv')

In [3]:
df.sample(5)

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,training_hours,target
18452,30562,city_90,0.698,NaN,Has relevent experience,Part time course,Graduate,STEM,7.0,50-99,NaN,42.0,0.0
8163,2254,city_64,NaN,NaN,Has relevent experience,no_enrollment,Graduate,STEM,6.0,50-99,Pvt Ltd,42.0,0.0
11715,20382,city_21,0.624,NaN,No relevent experience,Part time course,Graduate,STEM,0.0,NaN,NaN,89.0,1.0
16400,19803,city_16,0.910,NaN,Has relevent experience,no_enrollment,Graduate,Business Degree,4.0,100-500,Pvt Ltd,16.0,0.0
7699,30094,city_48,0.493,Male,Has relevent experience,no_enrollment,High School,NaN,5.0,NaN,NaN,18.0,0.0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19158 entries, 0 to 19157
Data columns (total 13 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   enrollee_id             19158 non-null  int64
 1   city                    19158 non-null  object
 2   city_development_index  18679 non-null  float64
 3   gender                  14650 non-null  object
 4   relevent_experience     19158 non-null  object
 5   enrolled_university     18772 non-null  object
 6   education_level         18698 non-null  object
 7   major_discipline        16345 non-null  object
 8   experience              19093 non-null  float64
 9   company_size            13220 non-null  object
 10  company_type            13018 non-null  object
 11  training_hours          18392 non-null  float64
 12  target                  19158 non-null  float64
dtypes: float64(4), int64(1), object(8)
memory usage: 1.9+ MB

In [5]:
df.isnull().mean()*100
# we can not removing more than 5 % missing values row

enrollee_id                0.000000
city                       0.000000
city_development_index     2.500261
gender                    23.530640
relevent_experience        0.000000
enrolled_university        2.014824
education_level            2.401086
major_discipline          14.683161
experience                 0.339284
company_size              30.994885
company_type              32.049274
training_hours             3.998330
target                     0.000000
dtype: float64

In [7]:
cols=[var for var in df.columns if df[var].isnull().mean()*100<5 and df[var].isnull().mean()*100>0]
cols

['city_development_index',
 'enrolled_university',
 'education_level',
 'experience',
 'training_hours']

In [8]:
new_DF=df[cols].dropna()

In [9]:
new_DF.shape ,df.shape

((17182, 5), (19158, 13))

In [10]:
new_DF

,city_development_index,enrolled_university,education_level,experience,training_hours
0,0.920,no_enrollment,Graduate,20.0,36.0
1,0.776,no_enrollment,Graduate,15.0,47.0
2,0.624,Full time course,Graduate,5.0,83.0
4,0.767,no_enrollment,Masters,20.0,8.0
5,0.764,Part time course,Graduate,11.0,24.0
...,...,...,...,...,...
19153,0.878,no_enrollment,Graduate,14.0,42.0
19154,0.920,no_enrollment,Graduate,14.0,52.0
19155,0.920,no_enrollment,Graduate,20.0,44.0
19156,0.802,no_enrollment,High School,0.0,97.0
19157,0.855,no_enrollment,Primary School,2.0,127.0

In [9]:
new_df=df[['city_development_index',
 'enrolled_university',
 'education_level',
 'experience',
 'training_hours']].dropna()

In [10]:
new_df.shape

(17182, 5)

# following  technique is not good it remove lagre amount of data

In [12]:
new_dfs=df.dropna()

In [14]:
new_dfs.shape

(8434, 13)