In [3]:
import pandas as pd
from sklearn.impute import KNNImputer,SimpleImputer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression 
from sklearn.metrics import accuracy_score

In [4]:
df=pd.read_csv('titanic_toy.csv')

In [5]:
df

      Age     Fare  Family  Survived
0    22.0   7.2500       1         0
1    38.0  71.2833       1         1
2    26.0   7.9250       0         1
3    35.0  53.1000       1         1
4    35.0   8.0500       0         0
..    ...      ...     ...       ...
886  27.0  13.0000       0         0
887  19.0  30.0000       0         1
888   NaN  23.4500       3         0
889  26.0      NaN       0         1
890  32.0   7.7500       0         0

[891 rows x 4 columns]

In [6]:
df.isnull().mean()*100

Age         19.865320
Fare         5.050505
Family       0.000000
Survived     0.000000
dtype: float64

In [11]:
df.drop(columns=['Fare'],inplace=True)

In [12]:
x=df.drop(columns=['Survived'])
y=df['Survived']

In [13]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [14]:
x_train

      Age  Family
140   NaN       2
439  31.0       0
817  31.0       2
378  20.0       0
491  21.0       0
..    ...     ...
835  39.0       2
192  19.0       1
629   NaN       0
559  36.0       1
684  60.0       2

[712 rows x 2 columns]

In [32]:
imputer=KNNImputer(n_neighbors=5,weights='distance')

x_train_trf=imputer.fit_transform(x_train)
x_test_trf=imputer.transform(x_test)

In [33]:
model=LogisticRegression()
model.fit(x_train_trf,y_train)
y_pred=model.predict(x_test_trf)
accuracy_score(y_test,y_pred)

0.6201117318435754

# without knn imputer

In [34]:
si=SimpleImputer()

In [35]:
x_train_trf2=si.fit_transform(x_train)
x_test_trf2=si.transform(x_test)

In [36]:
model2=LogisticRegression()

In [37]:
model2.fit(x_train_trf2,y_train)
y_pred=model2.predict(x_test_trf2)
accuracy_score(y_test,y_pred2)

0.6145251396648045