In [1]:
import pandas as pd 
import requests

In [2]:
response=requests.get("https://api.themoviedb.org/3/movie/popular?api_key=d1c9d59a2d61e9c42e6dbf0f1d6ce1e2")

In [3]:
response.json()

{'page': 1,
 'results': [{'adult': False,
   'backdrop_path': '/qeQJx07rK2xm8SD2sJxFKhE7gs0.jpg',
   'genre_ids': [878, 28, 12],
   'id': 969681,
   'title': 'Spider-Man: Brand New Day',
   'original_language': 'en',
   'original_title': 'Spider-Man: Brand New Day',
   'overview': "Fighting crime full-time as Spider-Man in a world that doesn't remember him—and the pressure of seeing his old friends move on without him—sparks a change in Peter Parker he may not have the power to control. But that transformation might also be the only thing that can stop a shocking new threat to the city and those he loves - a powerful villain no one can even see.",
   'popularity': 1146.6141,
   'poster_path': '/iPOn6DinuVyLY17YM9mKuPofV08.jpg',
   'release_date': '2026-07-29',
   'softcore': False,
   'video': False,
   'vote_average': 7.863,
   'vote_count': 1562},
  {'adult': False,
   'backdrop_path': '/RMXG8myu1aGlNUsRjtxzmpdMK0.jpg',
   'genre_ids': [12, 28, 14],
   'id': 1368337,
   'title': 'The Odyssey',
   'original_language': 'en',
   'original_title': 'The Odyssey',
   'overview': 'Odysseus, the legendary King of Ithaca, embarks on a long and perilous journey home following the Trojan War. Throughout his voyage, he is forced to confront the whims of gods, mythological monsters, and trials that stretch both his cunning and his humanity to the breaking point.',
   'popularity': 819.0049,
   'poster_path': '/5rhTDKUhPYvpdQIijFIs5VoWsON.jpg',
   'release_date': '2026-07-15',
   'softcore': False,
   'video': False,
   'vote_average': 7.992,
   'vote_count': 2633},
  {'adult': False,
   'backdrop_path': '/14QbnygCuTO0vl7CAFmPf1fgZfV.jpg',
   'genre_ids': [28, 12, 878],
   'id': 634649,
   'title': 'Spider-Man: No Way Home',
   'original_language': 'en',
   'original_title': 'Spider-Man: No Way Home',
   'overview': 'Peter Parker is unmasked and no longer able to separate his normal life from the high-stakes of being a super-hero. When he asks for help from Doctor Strange the stakes become even more dangerous, forcing him to discover what it truly means to be Spider-Man.',
   'popularity': 643.3186,
   'poster_path': '/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg',
   'release_date': '2021-12-15',
   'softcore': False,
   'video': False,
   'vote_average': 7.938,
   'vote_count': 22612},
  {'adult': False,
   'backdrop_path': '/2mPmccLg8QCD4ZF6v8kSsUijPPW.jpg',
   'genre_ids': [27, 878, 53],
   'id': 1284041,
   'title': 'The Last House',
   'original_language': 'en',
   'original_title': 'The Last House',
   'overview': 'A family suddenly sealed inside their home must work together to survive against dwindling resources and the ominous threat keeping them trapped.',
   'popularity': 383.9155,
   'poster_path': '/6JU7E8Vv2M11egkctWVOScxWR75.jpg',
   'release_date': '2026-08-06',
   'softcore': False,
   'video': False,
   'vote_average': 6.8,
   'vote_count': 456},
  {'adult': False,
   'backdrop_path': '/54KIfdTEzOliHDKx0OkzYGqAICx.jpg',
   'genre_ids': [28, 12, 878],
   'id': 1081003,
   'title': 'Supergirl',
   'original_language': 'en',
   'original_title': 'Supergirl',
   'overview': 'When an unexpected and ruthless adversary strikes too close to home, Kara Zor-El, aka Supergirl, reluctantly joins forces with an unlikely companion on an epic, interstellar journey of vengeance and justice.',
   'popularity': 287.6622,
   'poster_path': '/1QCWdqzTfh2x9UylVpspIU6QTuM.jpg',
   'release_date': '2026-06-24',
   'softcore': False,
   'video': False,
   'vote_average': 6.746,
   'vote_count': 1778},
  {'adult': False,
   'backdrop_path': '/8sSKdEmlmqF4kJUd28SqthXC4yZ.jpg',
   'genre_ids': [16, 10751, 35, 12],
   'id': 1084244,
   'title': 'Toy Story 5',
   'original_language': 'en',
   'original_title': 'Toy Story 5',
   'overview': "When Bonnie receives a Lilypad tablet as a gift and becomes obsessed, Buzz, Woody, Jessie and the rest of the gang's jobs become exponentially harder when they have to go head to head with the all-new threat to playtime.",
   'popularity': 294.9183,
   'poster_path': '/sfQtVlIHljToOwYjhe21KPGzZWK.jpg',
   'release_date': '2026-06-17',
   'softcore': False,
   'video': False,
   'vote_average': 7.419,
   'vote_count': 810},
  {'adult': False,
   'backdrop_path': '/cOKATn8lOcvVnOqqV5oYWaI9z2Z.jpg',
   'genre_ids': [28, 27, 878],
   'id': 1375646,
   'title': 'Colony',
   'original_language': 'ko',
   'original_title': '군체',
   'overview': 'Professor Se-jeong is thrust into a bloody nightmare when a rapidly mutating virus is released during a biotech conference causing authorities to seal the facility. Trapped inside with no escape, Se-jeong along with a small group of survivors must fight to stay alive while the infected undergo horrific transformations.',
   'popularity': 292.9874,
   'poster_path': '/wC69brhk65GvrgNQdqLRUqtneUH.jpg',
   'release_date': '2026-05-21',
   'softcore': False,
   'video': False,
   'vote_average': 8.125,
   'vote_count': 464},
  {'adult': False,
   'backdrop_path': '/biwEwIkjZhMUfXzz59bpeDzwYB6.jpg',
   'genre_ids': [27],
   'id': 1212763,
   'title': 'Evil Dead Burn',
   'original_language': 'en',
   'original_title': 'Evil Dead Burn',
   'overview': "After her husband's abrupt death, Alice seeks solace with his remaining family — descendants of a leading researcher on demonic possession. As her in-laws transform one by one into creatures that feed on fear, she comes to discover that the vows she took in life survive even in death.",
   'popularity': 270.5983,
   'poster_path': '/uRxrNXQWkHoENm3nwVOZDYSCx2F.jpg',
   'release_date': '2026-07-07',
   'softcore': False,
   'video': False,
   'vote_average': 7.897,
   'vote_count': 950},
  {'adult': False,
   'backdrop_path': '/lh3BDkmWJh998n4fQcHYcVi7dpm.jpg',
   'genre_ids': [12, 18, 28],
   'id': 1284465,
   'title': 'The Death of Robin Hood',
   'original_language': 'en',
   'original_title': 'The Death of Robin Hood',
   'overview': 'Grappling with his past after a life of crime and murder, Robin Hood finds himself gravely injured after a battle he thought would be his last. In the hands of a mysterious woman, he is offered a chance at salvation.',
   'popularity': 258.7221,
   'poster_path': '/92Tsfx7SFafOqWsotvrlJbHyehd.jpg',
   'release_date': '2026-06-18',
   'softcore': False,
   'video': False,
   'vote_average': 6.4,
   'vote_count': 192},
  {'adult': False,
   'backdrop_path': '/rZfmzpixLKLR3Hg2u0WgC7XLFl8.jpg',
   'genre_ids': [27, 53],
   'id': 1339713,
   'title': 'Obsession',
   'original_language': 'en',
   'original_title': 'Obsession',
   'overview': 'After breaking the mysterious "One Wish Willow" to win his crush\'s heart, a hopeless romantic finds himself getting exactly what he asked for but soon discovers that some desires come at a dark, sinister price.',
   'popularity': 262.6154,
   'poster_path': '/bRwnj8WEKBCvmfeUNOukJPwB43K.jpg',
   'release_date': '2026-05-13',
   'softcore': False,
   'video': False,
   'vote_average': 8.227,
   'vote_count': 4565},
  {'adult': False,
   'backdrop_path': '/flxau5Iu7bChQHsESqvGZ3FQRaI.jpg',
   'genre_ids': [878, 53],
   'id': 1275779,
   'title': 'Disclosure Day',
   'original_language': 'en',
   'original_title': 'Disclosure Day',
   'overview': "A cybersecurity expert becomes a whistleblower after uncovering secrets about aliens, putting him on the run from a corporation. Meanwhile, a meteorologist experiencing strange phenomena joins forces with him to prove there's life beyond our understanding.",
   'popularity': 246.4077,
   'poster_path': '/AnJ8IQJI23hNpYXVNaythu061Ru.jpg',
   'release_date': '2026-06-10',
   'softcore': False,
   'video': False,
   'vote_average': 7.448,
   'vote_count': 2675},
  {'adult': False,
   'backdrop_path': '/kkcwhgSFd81QDlXo8ytrpHPQjhy.jpg',
   'genre_ids': [12, 16, 35, 10751, 14],
   'id': 1315772,
   'title': 'Minions & Monsters',
   'original_language': 'en',
   'original_title': 'Minions & Monsters',
   'overview': 'This is the rambunctious, ridiculous and totally true story of how the Minions conquered Hollywood, became movie stars, lost everything, unleashed monsters onto the world and then banded together to try and save the planet from the mayhem they had just created.',
   'popularity': 331.3084,
   'poster_path': '/nz7i42yhLIJ4ve9JKgM6NthoLHO.jpg',
   'release_date': '2026-06-24',
   'softcore': False,
   'video': False,
   'vote_average': 6.985,
   'vote_count': 397},
  {'adult': False,
   'backdrop_path': '/c6BPbkO5Npt1OdwttAxCFo06wtH.jpg',
   'genre_ids': [10751, 14, 35, 12],
   'id': 1108427,
   'title': 'Moana',
   'original_language': 'en',
   'original_title': 'Moana',
   'overview': "Teenage Moana answers the Ocean's call and, for the first time, voyages beyond the reef of her island of Motunui with infamous demigod Maui on an unforgettable journey to restore prosperity to her people.",
   'popularity': 229.5025,
   'poster_path': '/zKVgiv5qHCvCLT4A2ymJi5QeXDH.jpg',
   'release_date': '2026-07-08',
   'softcore': False,
   'video': False,
   'vote_average': 6.0,
   'vote_count': 192},
  {'adult': False,
   'backdrop_path': '/fn4n6uOYcB6Uh89nbNPoU2w80RV.jpg',
   'genre_ids': [28, 12, 878],
   'id': 315635,
   'title': 'Spider-Man: Homecoming',
   'original_language': 'en',
   'original_title': 'Spider-Man: Homecoming',
   'overview': 'Following the events of Captain America: Civil War, Peter Parker, with the help of his mentor Tony Stark, tries to balance his life as an ordinary high school student in Queens, New York City, with fighting crime as his superhero alter ego Spider-Man as a new threat, the Vulture, emerges.',
   'popularity': 220.5926,
   'poster_path': '/c24sv2weTHPsmDa7jEMN0m2P3RT.jpg',
   'release_date': '2017-07-05',
   'softcore': False,
   'video': False,
   'vote_average': 7.332,
   'vote_count': 23588},
  {'adult': False,
   'backdrop_path': '/c4TkvRGVrghFY2qFKJ0SUwqtAiW.jpg',
   'genre_ids': [],
   'id': 1599191,
   'title': '仙逆剧场版 弑仙之战',
   'original_language': 'zh',
   'original_title': '仙逆剧场版 弑仙之战',
   'overview': '',
   'popularity': 188.0818,
   'poster_path': '/m1dXI1997D7lj6Sh0Z2DI26o2nI.jpg',
   'release_date': '',
   'softcore': False,
   'video': False,
   'vote_average': 0.0,
   'vote_count': 0},
  {'adult': False,
   'backdrop_path': '/se8LfmZYFiNerF6U7zMUKePV0vE.jpg',
   'genre_ids': [27, 53],
   'id': 1481343,
   'title': "The Devil's Mouth",
   'original_language': 'en',
   'original_title': "The Devil's Mouth",
   'overview': "A group of college friends' Thailand adventure turns deadly when they become trapped in submerged caves with a dangerous predator. As oxygen runs low, past conflicts emerge in their desperate fight for survival.",
   'popularity': 185.1919,
   'poster_path': '/lH8k9uCWYn2b2gsYleqYBDPbWa8.jpg',
   'release_date': '2026-07-29',
   'softcore': False,
   'video': False,
   'vote_average': 6.536,
   'vote_count': 571},
  {'adult': False,
   'backdrop_path': '/dqmMWNWfLnExDRpMtIMqI97GQFR.jpg',
   'genre_ids': [27, 9648, 878],
   'id': 1083381,
   'title': 'Backrooms',
   'original_language': 'en',
   'original_title': 'Backrooms',
   'overview': 'A strange doorway appears in the basement of a furniture showroom.',
   'popularity': 176.1763,
   'poster_path': '/rhGx6E3qRNMgj3i5su2oukNHwIQ.jpg',
   'release_date': '2026-05-27',
   'softcore': False,
   'video': False,
   'vote_average': 7.101,
   'vote_count': 2690},
  {'adult': False,
   'backdrop_path': '/7t6f6VxA2ZXbbZSVctgt7bZG2DI.jpg',
   'genre_ids': [27, 878, 53],
   'id': 1307118,
   'title': 'Soulm8te',
   'original_language': 'en',
   'original_title': 'Soulm8te',
   'overview': 'After a ruthless tech giant acquires a small robotics company, a grieving engineer is tasked with testing their new AI companion. But when he attempts to reprogram her to be a truly sentient soulmate, she develops needs of her own—unleashing a relentless spree of precision-engineered mayhem.',
   'popularity': 179.2709,
   'poster_path': '/bNErActDctl6cdUGw9pnjSCmyhQ.jpg',
   'release_date': '2026-07-31',
   'softcore': False,
   'video': False,
   'vote_average': 6.483,
   'vote_count': 90},
  {'adult': False,
   'backdrop_path': '/zQ8AxTPiCiS5nnwXpwTBPBHSaa5.jpg',
   'genre_ids': [28, 878],
   'id': 557,
   'title': 'Spider-Man',
   'original_language': 'en',
   'original_title': 'Spider-Man',
   'overview': 'After being bitten by a genetically altered spider at Oscorp, nerdy but endearing high school student Peter Parker is endowed with amazing powers to become the superhero known as Spider-Man.',
   'popularity': 169.7288,
   'poster_path': '/nXdAh5vUwERL4WGVMaee8RoDEAS.jpg',
   'release_date': '2002-05-01',
   'softcore': False,
   'video': False,
   'vote_average': 7.342,
   'vote_count': 21089},
  {'adult': False,
   'backdrop_path': '/rOIaKlAX0SeNC25dFbM0y1mFsH6.jpg',
   'genre_ids': [12, 14, 28],
   'id': 1698863,
   'title': 'The Odyssey',
   'original_language': 'en',
   'original_title': 'The Odyssey',
   'overview': 'Based on the Ancient Greek epic. After ten years of war, King Odysseus sets sail for Ithaca, eager to reunite with his beloved. But his journey home is far more treacherous than the battlefield, as he must face deadly monsters and vengeful gods to survive.',
   'popularity': 165.1631,
   'poster_path': '/xBHCRB7zLIW41w8QskfwJhm32YF.jpg',
   'release_date': '2026-07-03',
   'softcore': False,
   'video': False,
   'vote_average': 6.233,
   'vote_count': 15}],
 'total_pages': 58427,
 'total_results': 1168538}

In [4]:
dfs=pd.DataFrame(response.json()['results'])[['adult','id','genre_ids','title','original_title','release_date','overview']]

In [5]:
dfs.shape

(20, 7)

In [6]:
df=pd.DataFrame()

In [7]:
df

Empty DataFrame
Columns: []
Index: []

In [8]:
for i in range(1,5):
    response=requests.get(f"https://api.themoviedb.org/3/movie/popular?api_key=d1c9d59a2d61e9c42e6dbf0f1d6ce1e2&page={i}")
    temp_df=pd.DataFrame(response.json()['results'])[['adult','id','genre_ids','title','original_title','release_date','overview']]
    df=pd.concat([df,temp_df],ignore_index=True)

In [9]:
df.shape

(80, 7)

In [10]:
df

,adult,id,genre_ids,title,original_title,release_date,overview
0,False,969681,"[878, 28, 12]",Spider-Man: Brand New Day,Spider-Man: Brand New Day,2026-07-29,Fighting crime full-time as Spider-Man in a wo...
1,False,1368337,"[12, 28, 14]",The Odyssey,The Odyssey,2026-07-15,"Odysseus, the legendary King of Ithaca, embark..."
2,False,634649,"[28, 12, 878]",Spider-Man: No Way Home,Spider-Man: No Way Home,2021-12-15,Peter Parker is unmasked and no longer able to...
3,False,1284041,"[27, 878, 53]",The Last House,The Last House,2026-08-06,A family suddenly sealed inside their home mus...
4,False,1081003,"[28, 12, 878]",Supergirl,Supergirl,2026-06-24,When an unexpected and ruthless adversary stri...
...,...,...,...,...,...,...,...
75,False,155,"[28, 80, 53]",The Dark Knight,The Dark Knight,2008-07-16,Batman raises the stakes in his war on crime. ...
76,False,1304313,"[27, 9648]",Lee Cronin's The Mummy,Lee Cronin's The Mummy,2026-04-15,The young daughter of a journalist disappears ...
77,False,1007757,"[12, 16, 10751, 14]",Swapped,Swapped,2026-05-01,"A small woodland creature and a majestic bird,..."
78,False,1003596,"[878, 28, 12]",Avengers: Doomsday,Avengers: Doomsday,2026-12-16,Beloved heroes from three distinct universes a...
79,False,5721,[18],Vixen!,Vixen!,1968-10-15,"In a Canadian mountain resort, Vixen Palmer re..."